### ISSUE TITLE
how get merged_event.npy for GLUCOSE preprocessing step

### ISSUE THREAD

**Issue by SarikGhazarian** [HKUST-KnowComp/CSKB-Population#1]
Hi,

I am trying to preprocess GLUCOSE CSKB. As it is indicated in second step of its README (Parsed Matching step), we need to get the parser and merged eventuality cache from ASER and save it as merged_event.npy. My question is that how we can get the merged eventuality cache? In the provided link from ASER there isn't such a merged event.

thanks in advance!

**Comment by MighTy-Weaver** [comment]
Thanks for your question!
The merged_event.npy file can be downloaded at https://hkustconnect-my.sharepoint.com/:u:/g/personal/wwangbw_connect_ust_hk/EQE6rYNuzTRImQ4O4NuemM0BPdVKd9Un5_C1lhnJsKUT-A?e=yVfIwo

**Comment by SarikGhazarian** [comment]
Thank you! Really appreciate!


Sincerely,
Sarik Ghazarian
PhD Student in Computer Science 
Information Sciences Institute  
University of Southern California
