### ISSUE TITLE
Where to download train.csv

### ISSUE THREAD

**Issue by shaoyijia** [HKUST-KnowComp/CSKB-Population#2]
Hi,

Thank you for creating the benchmark dataset. 

I found the link (https://www.kaggle.com/datasets/tianqingfang/ckbp-emnlp2021) doesn't work anymore. Where can we download `train.csv` now?

Thanks for your help!

**Comment by tqfang** [comment]
Could you try this link again? Should be working now.

**Comment by shaoyijia** [comment]
Work very well. Thank you for your quick reply!
